# -*- coding: utf-8 -*-
"""Matriks inversion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xf4a6xL2VI08vazAsgi1T0EKpuHZDqdu
"""

import numpy as np
X = np.array([[6, 1], [0, 5]]) #Membuat matriks 2x2
print(X) #Menampilkan matriks 2x2
Xinv = np.linalg.inv(X) #Menghitung invers matriks
print(Xinv) #menampilkan invers matriks
print(np.dot(X, Xinv)) #Menampilkan perhitungan X dan Xinv
print("==========")
#Menyelesaikan persamaan menggunakan numpy
x = np.array([[4, 2], [-5, -3]]) #membuat matriks
print(x) #menampilkan matriks
y = np.array([4, -7]) #membuat vektor
print(y) #menampilkan vektor
print(np.linalg.solve(x, y)) #menampilkan solusi dari persamaan
print("==========")
#Menyelesaikan persamaan menggunakan torch
import torch
m = torch.tensor([[4.0, 2.0], [-5.0, -3.0]]) #membuat matriks
print(m) #menampilkan matriks
n = torch.tensor([4.0, -7.0]) #membuat vektor
print(n) #menampilkan vektor
print(torch.linalg.solve(m, n)) #menampilkan solusi dari persamaan
print("==========")
#Menyelesaikan persamaan menggunakan tensorflow
import tensorflow as tf
p = tf.Variable([[4.0, 2.0], [-5.0, -3.0]]) #membuat matriks
print(p) #menampilkan matriks
q = tf.Variable([[4.0], [-7.0]]) #membuat vektor
print(q) #menampilkan vektor
print(tf.linalg.solve(p, q)) #menampilkan solusi dari persamaan